BEGIN;

TRUNCATE public."Roles" RESTART IDENTITY CASCADE;
TRUNCATE public."Permisos" RESTART IDENTITY CASCADE;
TRUNCATE public."Usuarios" RESTART IDENTITY CASCADE;
TRUNCATE public."RolPermiso" RESTART IDENTITY CASCADE;
TRUNCATE public."UsuarioPermiso" RESTART IDENTITY CASCADE;
TRUNCATE public."Especialidades" RESTART IDENTITY CASCADE;
TRUNCATE public."Consultorios" RESTART IDENTITY CASCADE;
TRUNCATE public."Pacientes" RESTART IDENTITY CASCADE;
TRUNCATE public."Medicos" RESTART IDENTITY CASCADE;
TRUNCATE public."Horarios" RESTART IDENTITY CASCADE;
TRUNCATE public."AgendaCalendario" RESTART IDENTITY CASCADE;
TRUNCATE public."Citas" RESTART IDENTITY CASCADE;
TRUNCATE public."Pagos" RESTART IDENTITY CASCADE;

COMMIT;